services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    ports:
      - 3000:3000
  vanilla_scraper:
    <<: app
    command: bun run commands/scrapeVanilla.ts
  pufferfish_scraper:
    <<: app
    command: bun run commands/scrapePufferfish.ts
  paper_scraper:
    <<: app
    command: bun run commands/scrapePaper.ts