on: push
concurrency: 
  cancel-in-progress: true
  group: development
jobs:
  job:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: oven-sh/setup-bun@v1

      - name: Checkout
        uses: actions/checkout@v4

      - name: Test
        run: |
          bun install
          bun run test:cov