on: push
concurrency: 
  cancel-in-progress: true
  group: development
jobs:
  job:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: oven-sh/setup-bun@v1
      - name: Checkout
        uses: actions/checkout@v4
      - name: Test
        env:
            R2_ACCESS_KEY: ${{ secrets.R2_ACCESS_KEY }}
            R2_SECRET_KEY: ${{ secrets.R2_SECRET_KEY }}
            R2_ACCOUNT_ID: ${{ vars.R2_ACCOUNT_ID }}
            R2_BUCKET_NAME: ${{ vars.R2_BUCKET_NAME }}
        run: |
          bun install
          bun run test:cov
