on: push
concurrency: 
  cancel-in-progress: true
  group: main
jobs:
  node:
    name: NPM Jobs
    uses: minere-cloud/ci-cd/.github/workflows/node.yaml@master
  test:
    name: Test
    runs-on: ubuntu-latest
    needs: [node]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v3
        id: node-dependecies
        with:
          path: ./node_modules/*
          key: ${{ github.sha }}
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - env:
            R2_ACCESS_KEY: ${{ secrets.R2_ACCESS_KEY }}
            R2_SECRET_KEY: ${{ secrets.R2_SECRET_KEY }}
            R2_ACCOUNT_ID: ${{ vars.R2_ACCOUNT_ID }}
            R2_SERVER_JAR_BUCKET_NAME: ${{ vars.R2_SERVER_JAR_BUCKET_NAME }}
            R2_SERVER_TEMPLATE_BUCKET_NAME: ${{ vars.R2_SERVER_TEMPLATE_BUCKET_NAME }}  
        run: |
          npm run test:cov

  docker-build:
    permissions:
      contents: read
      packages: write
      id-token: write
    needs: [node, test]
    name: Docker Build
    uses: minere-cloud/ci-cd/.github/workflows/docker.yaml@master
    with:
      development: true
      production: false

